data_path:
  bulk_data_path: "/path/to/bulk_data"
  sc_data_path: "/path/to/sc_data"

software_path:
  buddi_HGSC: "/home/weishanli/CU/DavidsonLab/BuddiHGSC/buddi_HGSC"
  buddi_v2: "/home/weishanli/CU/DavidsonLab/buddi_v2/src"