data_path:
  bulk_data_path: "/home/weishanli/CU/DavidsonLab/BuddiHGSC/data/bulk"
  sc_data_path: "/home/weishanli/CU/DavidsonLab/BuddiHGSC/data/sc"

software_path:
  buddi_HGSC: "/home/weishanli/CU/DavidsonLab/BuddiHGSC/buddi_HGSC"